// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogposts.proto

// Protobuf Java Version: 3.25.1
package de.samples.apicomparison.provider.boundary.grpc.stub;

public interface AuthorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Author)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UUID id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.UUID id = 1;</code>
   * @return The id.
   */
  de.samples.apicomparison.provider.boundary.grpc.stub.UUID getId();
  /**
   * <code>.UUID id = 1;</code>
   */
  de.samples.apicomparison.provider.boundary.grpc.stub.UUIDOrBuilder getIdOrBuilder();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string description = 3;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
