// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogposts.proto

// Protobuf Java Version: 3.25.1
package de.samples.apicomparison.provider.boundary.grpc.stub;

/**
 * Protobuf type {@code BlogPost}
 */
public final class BlogPost extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BlogPost)
    BlogPostOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlogPost.newBuilder() to construct.
  private BlogPost(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlogPost() {
    title_ = "";
    content_ = "";
    hashTags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BlogPost();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.samples.apicomparison.provider.boundary.grpc.stub.Blogposts.internal_static_BlogPost_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.samples.apicomparison.provider.boundary.grpc.stub.Blogposts.internal_static_BlogPost_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost.class, de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private de.samples.apicomparison.provider.boundary.grpc.stub.UUID id_;
  /**
   * <code>.UUID id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.UUID id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public de.samples.apicomparison.provider.boundary.grpc.stub.UUID getId() {
    return id_ == null ? de.samples.apicomparison.provider.boundary.grpc.stub.UUID.getDefaultInstance() : id_;
  }
  /**
   * <code>.UUID id = 1;</code>
   */
  @java.lang.Override
  public de.samples.apicomparison.provider.boundary.grpc.stub.UUIDOrBuilder getIdOrBuilder() {
    return id_ == null ? de.samples.apicomparison.provider.boundary.grpc.stub.UUID.getDefaultInstance() : id_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object content_ = "";
  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp timestamp_;
  /**
   * <code>.Timestamp timestamp = 4;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.Timestamp timestamp = 4;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp getTimestamp() {
    return timestamp_ == null ? de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.Timestamp timestamp = 4;</code>
   */
  @java.lang.Override
  public de.samples.apicomparison.provider.boundary.grpc.stub.TimestampOrBuilder getTimestampOrBuilder() {
    return timestamp_ == null ? de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp.getDefaultInstance() : timestamp_;
  }

  public static final int AUTHOR_FIELD_NUMBER = 5;
  private de.samples.apicomparison.provider.boundary.grpc.stub.Author author_;
  /**
   * <code>optional .Author author = 5;</code>
   * @return Whether the author field is set.
   */
  @java.lang.Override
  public boolean hasAuthor() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .Author author = 5;</code>
   * @return The author.
   */
  @java.lang.Override
  public de.samples.apicomparison.provider.boundary.grpc.stub.Author getAuthor() {
    return author_ == null ? de.samples.apicomparison.provider.boundary.grpc.stub.Author.getDefaultInstance() : author_;
  }
  /**
   * <code>optional .Author author = 5;</code>
   */
  @java.lang.Override
  public de.samples.apicomparison.provider.boundary.grpc.stub.AuthorOrBuilder getAuthorOrBuilder() {
    return author_ == null ? de.samples.apicomparison.provider.boundary.grpc.stub.Author.getDefaultInstance() : author_;
  }

  public static final int HASHTAGS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList hashTags_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string hashTags = 6;</code>
   * @return A list containing the hashTags.
   */
  public com.google.protobuf.ProtocolStringList
      getHashTagsList() {
    return hashTags_;
  }
  /**
   * <code>repeated string hashTags = 6;</code>
   * @return The count of hashTags.
   */
  public int getHashTagsCount() {
    return hashTags_.size();
  }
  /**
   * <code>repeated string hashTags = 6;</code>
   * @param index The index of the element to return.
   * @return The hashTags at the given index.
   */
  public java.lang.String getHashTags(int index) {
    return hashTags_.get(index);
  }
  /**
   * <code>repeated string hashTags = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the hashTags at the given index.
   */
  public com.google.protobuf.ByteString
      getHashTagsBytes(int index) {
    return hashTags_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getId());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getTimestamp());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(5, getAuthor());
    }
    for (int i = 0; i < hashTags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, hashTags_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTimestamp());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getAuthor());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < hashTags_.size(); i++) {
        dataSize += computeStringSizeNoTag(hashTags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getHashTagsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost)) {
      return super.equals(obj);
    }
    de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost other = (de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (hasAuthor() != other.hasAuthor()) return false;
    if (hasAuthor()) {
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
    }
    if (!getHashTagsList()
        .equals(other.getHashTagsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (hasAuthor()) {
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
    }
    if (getHashTagsCount() > 0) {
      hash = (37 * hash) + HASHTAGS_FIELD_NUMBER;
      hash = (53 * hash) + getHashTagsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BlogPost}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BlogPost)
      de.samples.apicomparison.provider.boundary.grpc.stub.BlogPostOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.samples.apicomparison.provider.boundary.grpc.stub.Blogposts.internal_static_BlogPost_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.samples.apicomparison.provider.boundary.grpc.stub.Blogposts.internal_static_BlogPost_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost.class, de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost.Builder.class);
    }

    // Construct using de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIdFieldBuilder();
        getTimestampFieldBuilder();
        getAuthorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      title_ = "";
      content_ = "";
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      author_ = null;
      if (authorBuilder_ != null) {
        authorBuilder_.dispose();
        authorBuilder_ = null;
      }
      hashTags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.samples.apicomparison.provider.boundary.grpc.stub.Blogposts.internal_static_BlogPost_descriptor;
    }

    @java.lang.Override
    public de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost getDefaultInstanceForType() {
      return de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost.getDefaultInstance();
    }

    @java.lang.Override
    public de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost build() {
      de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost buildPartial() {
      de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost result = new de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = idBuilder_ == null
            ? id_
            : idBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.content_ = content_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.timestamp_ = timestampBuilder_ == null
            ? timestamp_
            : timestampBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.author_ = authorBuilder_ == null
            ? author_
            : authorBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        hashTags_.makeImmutable();
        result.hashTags_ = hashTags_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost) {
        return mergeFrom((de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost other) {
      if (other == de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.hasAuthor()) {
        mergeAuthor(other.getAuthor());
      }
      if (!other.hashTags_.isEmpty()) {
        if (hashTags_.isEmpty()) {
          hashTags_ = other.hashTags_;
          bitField0_ |= 0x00000020;
        } else {
          ensureHashTagsIsMutable();
          hashTags_.addAll(other.hashTags_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              content_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getTimestampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getAuthorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureHashTagsIsMutable();
              hashTags_.add(s);
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private de.samples.apicomparison.provider.boundary.grpc.stub.UUID id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        de.samples.apicomparison.provider.boundary.grpc.stub.UUID, de.samples.apicomparison.provider.boundary.grpc.stub.UUID.Builder, de.samples.apicomparison.provider.boundary.grpc.stub.UUIDOrBuilder> idBuilder_;
    /**
     * <code>.UUID id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.UUID id = 1;</code>
     * @return The id.
     */
    public de.samples.apicomparison.provider.boundary.grpc.stub.UUID getId() {
      if (idBuilder_ == null) {
        return id_ == null ? de.samples.apicomparison.provider.boundary.grpc.stub.UUID.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.UUID id = 1;</code>
     */
    public Builder setId(de.samples.apicomparison.provider.boundary.grpc.stub.UUID value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
      } else {
        idBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.UUID id = 1;</code>
     */
    public Builder setId(
        de.samples.apicomparison.provider.boundary.grpc.stub.UUID.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.UUID id = 1;</code>
     */
    public Builder mergeId(de.samples.apicomparison.provider.boundary.grpc.stub.UUID value) {
      if (idBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          id_ != null &&
          id_ != de.samples.apicomparison.provider.boundary.grpc.stub.UUID.getDefaultInstance()) {
          getIdBuilder().mergeFrom(value);
        } else {
          id_ = value;
        }
      } else {
        idBuilder_.mergeFrom(value);
      }
      if (id_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.UUID id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.UUID id = 1;</code>
     */
    public de.samples.apicomparison.provider.boundary.grpc.stub.UUID.Builder getIdBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.UUID id = 1;</code>
     */
    public de.samples.apicomparison.provider.boundary.grpc.stub.UUIDOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            de.samples.apicomparison.provider.boundary.grpc.stub.UUID.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.UUID id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        de.samples.apicomparison.provider.boundary.grpc.stub.UUID, de.samples.apicomparison.provider.boundary.grpc.stub.UUID.Builder, de.samples.apicomparison.provider.boundary.grpc.stub.UUIDOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            de.samples.apicomparison.provider.boundary.grpc.stub.UUID, de.samples.apicomparison.provider.boundary.grpc.stub.UUID.Builder, de.samples.apicomparison.provider.boundary.grpc.stub.UUIDOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string content = 3;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      content_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp, de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp.Builder, de.samples.apicomparison.provider.boundary.grpc.stub.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.Timestamp timestamp = 4;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.Timestamp timestamp = 4;</code>
     * @return The timestamp.
     */
    public de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.Timestamp timestamp = 4;</code>
     */
    public Builder setTimestamp(de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
      } else {
        timestampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.Timestamp timestamp = 4;</code>
     */
    public Builder setTimestamp(
        de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.Timestamp timestamp = 4;</code>
     */
    public Builder mergeTimestamp(de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          timestamp_ != null &&
          timestamp_ != de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp.getDefaultInstance()) {
          getTimestampBuilder().mergeFrom(value);
        } else {
          timestamp_ = value;
        }
      } else {
        timestampBuilder_.mergeFrom(value);
      }
      if (timestamp_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Timestamp timestamp = 4;</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Timestamp timestamp = 4;</code>
     */
    public de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp.Builder getTimestampBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.Timestamp timestamp = 4;</code>
     */
    public de.samples.apicomparison.provider.boundary.grpc.stub.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.Timestamp timestamp = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp, de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp.Builder, de.samples.apicomparison.provider.boundary.grpc.stub.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp, de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp.Builder, de.samples.apicomparison.provider.boundary.grpc.stub.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private de.samples.apicomparison.provider.boundary.grpc.stub.Author author_;
    private com.google.protobuf.SingleFieldBuilderV3<
        de.samples.apicomparison.provider.boundary.grpc.stub.Author, de.samples.apicomparison.provider.boundary.grpc.stub.Author.Builder, de.samples.apicomparison.provider.boundary.grpc.stub.AuthorOrBuilder> authorBuilder_;
    /**
     * <code>optional .Author author = 5;</code>
     * @return Whether the author field is set.
     */
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .Author author = 5;</code>
     * @return The author.
     */
    public de.samples.apicomparison.provider.boundary.grpc.stub.Author getAuthor() {
      if (authorBuilder_ == null) {
        return author_ == null ? de.samples.apicomparison.provider.boundary.grpc.stub.Author.getDefaultInstance() : author_;
      } else {
        return authorBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Author author = 5;</code>
     */
    public Builder setAuthor(de.samples.apicomparison.provider.boundary.grpc.stub.Author value) {
      if (authorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        author_ = value;
      } else {
        authorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Author author = 5;</code>
     */
    public Builder setAuthor(
        de.samples.apicomparison.provider.boundary.grpc.stub.Author.Builder builderForValue) {
      if (authorBuilder_ == null) {
        author_ = builderForValue.build();
      } else {
        authorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Author author = 5;</code>
     */
    public Builder mergeAuthor(de.samples.apicomparison.provider.boundary.grpc.stub.Author value) {
      if (authorBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          author_ != null &&
          author_ != de.samples.apicomparison.provider.boundary.grpc.stub.Author.getDefaultInstance()) {
          getAuthorBuilder().mergeFrom(value);
        } else {
          author_ = value;
        }
      } else {
        authorBuilder_.mergeFrom(value);
      }
      if (author_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .Author author = 5;</code>
     */
    public Builder clearAuthor() {
      bitField0_ = (bitField0_ & ~0x00000010);
      author_ = null;
      if (authorBuilder_ != null) {
        authorBuilder_.dispose();
        authorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .Author author = 5;</code>
     */
    public de.samples.apicomparison.provider.boundary.grpc.stub.Author.Builder getAuthorBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getAuthorFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Author author = 5;</code>
     */
    public de.samples.apicomparison.provider.boundary.grpc.stub.AuthorOrBuilder getAuthorOrBuilder() {
      if (authorBuilder_ != null) {
        return authorBuilder_.getMessageOrBuilder();
      } else {
        return author_ == null ?
            de.samples.apicomparison.provider.boundary.grpc.stub.Author.getDefaultInstance() : author_;
      }
    }
    /**
     * <code>optional .Author author = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        de.samples.apicomparison.provider.boundary.grpc.stub.Author, de.samples.apicomparison.provider.boundary.grpc.stub.Author.Builder, de.samples.apicomparison.provider.boundary.grpc.stub.AuthorOrBuilder> 
        getAuthorFieldBuilder() {
      if (authorBuilder_ == null) {
        authorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            de.samples.apicomparison.provider.boundary.grpc.stub.Author, de.samples.apicomparison.provider.boundary.grpc.stub.Author.Builder, de.samples.apicomparison.provider.boundary.grpc.stub.AuthorOrBuilder>(
                getAuthor(),
                getParentForChildren(),
                isClean());
        author_ = null;
      }
      return authorBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList hashTags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureHashTagsIsMutable() {
      if (!hashTags_.isModifiable()) {
        hashTags_ = new com.google.protobuf.LazyStringArrayList(hashTags_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated string hashTags = 6;</code>
     * @return A list containing the hashTags.
     */
    public com.google.protobuf.ProtocolStringList
        getHashTagsList() {
      hashTags_.makeImmutable();
      return hashTags_;
    }
    /**
     * <code>repeated string hashTags = 6;</code>
     * @return The count of hashTags.
     */
    public int getHashTagsCount() {
      return hashTags_.size();
    }
    /**
     * <code>repeated string hashTags = 6;</code>
     * @param index The index of the element to return.
     * @return The hashTags at the given index.
     */
    public java.lang.String getHashTags(int index) {
      return hashTags_.get(index);
    }
    /**
     * <code>repeated string hashTags = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the hashTags at the given index.
     */
    public com.google.protobuf.ByteString
        getHashTagsBytes(int index) {
      return hashTags_.getByteString(index);
    }
    /**
     * <code>repeated string hashTags = 6;</code>
     * @param index The index to set the value at.
     * @param value The hashTags to set.
     * @return This builder for chaining.
     */
    public Builder setHashTags(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureHashTagsIsMutable();
      hashTags_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string hashTags = 6;</code>
     * @param value The hashTags to add.
     * @return This builder for chaining.
     */
    public Builder addHashTags(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureHashTagsIsMutable();
      hashTags_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string hashTags = 6;</code>
     * @param values The hashTags to add.
     * @return This builder for chaining.
     */
    public Builder addAllHashTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureHashTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, hashTags_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string hashTags = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearHashTags() {
      hashTags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string hashTags = 6;</code>
     * @param value The bytes of the hashTags to add.
     * @return This builder for chaining.
     */
    public Builder addHashTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureHashTagsIsMutable();
      hashTags_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BlogPost)
  }

  // @@protoc_insertion_point(class_scope:BlogPost)
  private static final de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost();
  }

  public static de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlogPost>
      PARSER = new com.google.protobuf.AbstractParser<BlogPost>() {
    @java.lang.Override
    public BlogPost parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BlogPost> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlogPost> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.samples.apicomparison.provider.boundary.grpc.stub.BlogPost getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

