// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogposts.proto

// Protobuf Java Version: 3.25.1
package de.samples.apicomparison.provider.boundary.grpc.stub;

public interface BlogPostInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BlogPostInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>optional .UUID author_id = 5;</code>
   * @return Whether the authorId field is set.
   */
  boolean hasAuthorId();
  /**
   * <code>optional .UUID author_id = 5;</code>
   * @return The authorId.
   */
  de.samples.apicomparison.provider.boundary.grpc.stub.UUID getAuthorId();
  /**
   * <code>optional .UUID author_id = 5;</code>
   */
  de.samples.apicomparison.provider.boundary.grpc.stub.UUIDOrBuilder getAuthorIdOrBuilder();

  /**
   * <code>repeated string hashTags = 6;</code>
   * @return A list containing the hashTags.
   */
  java.util.List<java.lang.String>
      getHashTagsList();
  /**
   * <code>repeated string hashTags = 6;</code>
   * @return The count of hashTags.
   */
  int getHashTagsCount();
  /**
   * <code>repeated string hashTags = 6;</code>
   * @param index The index of the element to return.
   * @return The hashTags at the given index.
   */
  java.lang.String getHashTags(int index);
  /**
   * <code>repeated string hashTags = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the hashTags at the given index.
   */
  com.google.protobuf.ByteString
      getHashTagsBytes(int index);
}
