// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogposts.proto

// Protobuf Java Version: 3.25.1
package de.samples.apicomparison.provider.boundary.grpc.stub;

public interface BlogPostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BlogPost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UUID id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.UUID id = 1;</code>
   * @return The id.
   */
  de.samples.apicomparison.provider.boundary.grpc.stub.UUID getId();
  /**
   * <code>.UUID id = 1;</code>
   */
  de.samples.apicomparison.provider.boundary.grpc.stub.UUIDOrBuilder getIdOrBuilder();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>.Timestamp timestamp = 4;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.Timestamp timestamp = 4;</code>
   * @return The timestamp.
   */
  de.samples.apicomparison.provider.boundary.grpc.stub.Timestamp getTimestamp();
  /**
   * <code>.Timestamp timestamp = 4;</code>
   */
  de.samples.apicomparison.provider.boundary.grpc.stub.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>optional .Author author = 5;</code>
   * @return Whether the author field is set.
   */
  boolean hasAuthor();
  /**
   * <code>optional .Author author = 5;</code>
   * @return The author.
   */
  de.samples.apicomparison.provider.boundary.grpc.stub.Author getAuthor();
  /**
   * <code>optional .Author author = 5;</code>
   */
  de.samples.apicomparison.provider.boundary.grpc.stub.AuthorOrBuilder getAuthorOrBuilder();

  /**
   * <code>repeated .HashTag hashTags = 6;</code>
   */
  java.util.List<de.samples.apicomparison.provider.boundary.grpc.stub.HashTag> 
      getHashTagsList();
  /**
   * <code>repeated .HashTag hashTags = 6;</code>
   */
  de.samples.apicomparison.provider.boundary.grpc.stub.HashTag getHashTags(int index);
  /**
   * <code>repeated .HashTag hashTags = 6;</code>
   */
  int getHashTagsCount();
  /**
   * <code>repeated .HashTag hashTags = 6;</code>
   */
  java.util.List<? extends de.samples.apicomparison.provider.boundary.grpc.stub.HashTagOrBuilder> 
      getHashTagsOrBuilderList();
  /**
   * <code>repeated .HashTag hashTags = 6;</code>
   */
  de.samples.apicomparison.provider.boundary.grpc.stub.HashTagOrBuilder getHashTagsOrBuilder(
      int index);
}
