// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogposts.proto

// Protobuf Java Version: 3.25.1
package de.samples.apicomparison.provider.boundary.grpc.stub;

public interface HashTagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HashTag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string description = 2;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
