// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogposts.proto

// Protobuf Java Version: 3.25.1
package de.samples.apicomparison.provider.boundary.grpc.stub;

public interface TimestampOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Timestamp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 seconds = 1;</code>
   * @return The seconds.
   */
  long getSeconds();

  /**
   * <code>int32 nanos = 2;</code>
   * @return The nanos.
   */
  int getNanos();
}
