
package de.samples.apicomparison.provider.boundary.soap.stubs;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BlogPostServiceInterface", targetNamespace = "http://samples.de/spring/soap/blog/service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BlogPostServiceInterface {


    /**
     * 
     * @param findAllInputPart
     * @return
     *     returns de.samples.apicomparison.provider.boundary.soap.stubs.FindAllBlogPostsResponse
     */
    @WebMethod(action = "findAll")
    @WebResult(name = "findAllBlogPostsResponse", targetNamespace = "http://samples.de/spring/soap/blog/messages", partName = "findAllOutputPart")
    public FindAllBlogPostsResponse findAll(
        @WebParam(name = "findAllBlogPostsRequest", targetNamespace = "http://samples.de/spring/soap/blog/messages", partName = "findAllInputPart")
        FindAllBlogPostsRequest findAllInputPart);

    /**
     * 
     * @param input
     */
    @WebMethod(action = "create")
    @Oneway
    public void create(
        @WebParam(name = "createBlogPostRequest", targetNamespace = "http://samples.de/spring/soap/blog/messages", partName = "input")
        CreateBlogPostRequest input);

    /**
     * 
     * @param id
     */
    @WebMethod(action = "deleteById")
    @Oneway
    public void deleteById(
        @WebParam(name = "deleteBlogPostRequest", targetNamespace = "http://samples.de/spring/soap/blog/messages", partName = "id")
        DeleteBlogPostRequest id);

}
