application:
  webclient:
    timeout: 2000
    base-url: http://localhost:8081
  apis:
    rest:
      endpoint: /api
    graphql:
      end-point: /graphql
    soap:
      end-point: /ws
logging:
  level:
    org.springframework.web.reactive.function.client: debug
    de.samples.apicomparison.consumer.clients.soap.config.encoding: debug
