application:
  webclient:
    timeout: 2000
    base-url: http://localhost:8081
  apis:
    rest:
      endpoint: /api
    graphql:
      end-point: /graphql
logging:
  level:
    org.springframework.web.reactive.function.client: debug
