// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogposts.proto

// Protobuf Java Version: 3.25.1
package de.samples.apicomparison.consumer.clients.grpc.stub;

public interface BlogPostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BlogPost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UUID id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.UUID id = 1;</code>
   * @return The id.
   */
  de.samples.apicomparison.consumer.clients.grpc.stub.UUID getId();
  /**
   * <code>.UUID id = 1;</code>
   */
  de.samples.apicomparison.consumer.clients.grpc.stub.UUIDOrBuilder getIdOrBuilder();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>.Timestamp timestamp = 4;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.Timestamp timestamp = 4;</code>
   * @return The timestamp.
   */
  de.samples.apicomparison.consumer.clients.grpc.stub.Timestamp getTimestamp();
  /**
   * <code>.Timestamp timestamp = 4;</code>
   */
  de.samples.apicomparison.consumer.clients.grpc.stub.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>optional .Author author = 5;</code>
   * @return Whether the author field is set.
   */
  boolean hasAuthor();
  /**
   * <code>optional .Author author = 5;</code>
   * @return The author.
   */
  de.samples.apicomparison.consumer.clients.grpc.stub.Author getAuthor();
  /**
   * <code>optional .Author author = 5;</code>
   */
  de.samples.apicomparison.consumer.clients.grpc.stub.AuthorOrBuilder getAuthorOrBuilder();

  /**
   * <code>repeated string hashTags = 6;</code>
   * @return A list containing the hashTags.
   */
  java.util.List<java.lang.String>
      getHashTagsList();
  /**
   * <code>repeated string hashTags = 6;</code>
   * @return The count of hashTags.
   */
  int getHashTagsCount();
  /**
   * <code>repeated string hashTags = 6;</code>
   * @param index The index of the element to return.
   * @return The hashTags at the given index.
   */
  java.lang.String getHashTags(int index);
  /**
   * <code>repeated string hashTags = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the hashTags at the given index.
   */
  com.google.protobuf.ByteString
      getHashTagsBytes(int index);
}
