// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogposts.proto

// Protobuf Java Version: 3.25.1
package de.samples.apicomparison.consumer.clients.grpc.stub;

public interface ListOfBlogPostsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListOfBlogPosts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .BlogPost blogPost = 1;</code>
   */
  java.util.List<de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost> 
      getBlogPostList();
  /**
   * <code>repeated .BlogPost blogPost = 1;</code>
   */
  de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost getBlogPost(int index);
  /**
   * <code>repeated .BlogPost blogPost = 1;</code>
   */
  int getBlogPostCount();
  /**
   * <code>repeated .BlogPost blogPost = 1;</code>
   */
  java.util.List<? extends de.samples.apicomparison.consumer.clients.grpc.stub.BlogPostOrBuilder> 
      getBlogPostOrBuilderList();
  /**
   * <code>repeated .BlogPost blogPost = 1;</code>
   */
  de.samples.apicomparison.consumer.clients.grpc.stub.BlogPostOrBuilder getBlogPostOrBuilder(
      int index);
}
