// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogposts.proto

// Protobuf Java Version: 3.25.1
package de.samples.apicomparison.consumer.clients.grpc.stub;

/**
 * <pre>
 *
 *  S E R V I C E
 * </pre>
 *
 * Protobuf type {@code ListOfBlogPosts}
 */
public final class ListOfBlogPosts extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListOfBlogPosts)
    ListOfBlogPostsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListOfBlogPosts.newBuilder() to construct.
  private ListOfBlogPosts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListOfBlogPosts() {
    blogPost_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListOfBlogPosts();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.samples.apicomparison.consumer.clients.grpc.stub.Blogposts.internal_static_ListOfBlogPosts_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.samples.apicomparison.consumer.clients.grpc.stub.Blogposts.internal_static_ListOfBlogPosts_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts.class, de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts.Builder.class);
  }

  public static final int BLOGPOST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost> blogPost_;
  /**
   * <code>repeated .BlogPost blogPost = 1;</code>
   */
  @java.lang.Override
  public java.util.List<de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost> getBlogPostList() {
    return blogPost_;
  }
  /**
   * <code>repeated .BlogPost blogPost = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends de.samples.apicomparison.consumer.clients.grpc.stub.BlogPostOrBuilder> 
      getBlogPostOrBuilderList() {
    return blogPost_;
  }
  /**
   * <code>repeated .BlogPost blogPost = 1;</code>
   */
  @java.lang.Override
  public int getBlogPostCount() {
    return blogPost_.size();
  }
  /**
   * <code>repeated .BlogPost blogPost = 1;</code>
   */
  @java.lang.Override
  public de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost getBlogPost(int index) {
    return blogPost_.get(index);
  }
  /**
   * <code>repeated .BlogPost blogPost = 1;</code>
   */
  @java.lang.Override
  public de.samples.apicomparison.consumer.clients.grpc.stub.BlogPostOrBuilder getBlogPostOrBuilder(
      int index) {
    return blogPost_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < blogPost_.size(); i++) {
      output.writeMessage(1, blogPost_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < blogPost_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, blogPost_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts)) {
      return super.equals(obj);
    }
    de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts other = (de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts) obj;

    if (!getBlogPostList()
        .equals(other.getBlogPostList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBlogPostCount() > 0) {
      hash = (37 * hash) + BLOGPOST_FIELD_NUMBER;
      hash = (53 * hash) + getBlogPostList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *
   *  S E R V I C E
   * </pre>
   *
   * Protobuf type {@code ListOfBlogPosts}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListOfBlogPosts)
      de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPostsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.samples.apicomparison.consumer.clients.grpc.stub.Blogposts.internal_static_ListOfBlogPosts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.samples.apicomparison.consumer.clients.grpc.stub.Blogposts.internal_static_ListOfBlogPosts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts.class, de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts.Builder.class);
    }

    // Construct using de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (blogPostBuilder_ == null) {
        blogPost_ = java.util.Collections.emptyList();
      } else {
        blogPost_ = null;
        blogPostBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.samples.apicomparison.consumer.clients.grpc.stub.Blogposts.internal_static_ListOfBlogPosts_descriptor;
    }

    @java.lang.Override
    public de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts getDefaultInstanceForType() {
      return de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts.getDefaultInstance();
    }

    @java.lang.Override
    public de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts build() {
      de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts buildPartial() {
      de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts result = new de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts result) {
      if (blogPostBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          blogPost_ = java.util.Collections.unmodifiableList(blogPost_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.blogPost_ = blogPost_;
      } else {
        result.blogPost_ = blogPostBuilder_.build();
      }
    }

    private void buildPartial0(de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts) {
        return mergeFrom((de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts other) {
      if (other == de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts.getDefaultInstance()) return this;
      if (blogPostBuilder_ == null) {
        if (!other.blogPost_.isEmpty()) {
          if (blogPost_.isEmpty()) {
            blogPost_ = other.blogPost_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBlogPostIsMutable();
            blogPost_.addAll(other.blogPost_);
          }
          onChanged();
        }
      } else {
        if (!other.blogPost_.isEmpty()) {
          if (blogPostBuilder_.isEmpty()) {
            blogPostBuilder_.dispose();
            blogPostBuilder_ = null;
            blogPost_ = other.blogPost_;
            bitField0_ = (bitField0_ & ~0x00000001);
            blogPostBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBlogPostFieldBuilder() : null;
          } else {
            blogPostBuilder_.addAllMessages(other.blogPost_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost m =
                  input.readMessage(
                      de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.parser(),
                      extensionRegistry);
              if (blogPostBuilder_ == null) {
                ensureBlogPostIsMutable();
                blogPost_.add(m);
              } else {
                blogPostBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost> blogPost_ =
      java.util.Collections.emptyList();
    private void ensureBlogPostIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        blogPost_ = new java.util.ArrayList<de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost>(blogPost_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost, de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.Builder, de.samples.apicomparison.consumer.clients.grpc.stub.BlogPostOrBuilder> blogPostBuilder_;

    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public java.util.List<de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost> getBlogPostList() {
      if (blogPostBuilder_ == null) {
        return java.util.Collections.unmodifiableList(blogPost_);
      } else {
        return blogPostBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public int getBlogPostCount() {
      if (blogPostBuilder_ == null) {
        return blogPost_.size();
      } else {
        return blogPostBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost getBlogPost(int index) {
      if (blogPostBuilder_ == null) {
        return blogPost_.get(index);
      } else {
        return blogPostBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public Builder setBlogPost(
        int index, de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost value) {
      if (blogPostBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlogPostIsMutable();
        blogPost_.set(index, value);
        onChanged();
      } else {
        blogPostBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public Builder setBlogPost(
        int index, de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.Builder builderForValue) {
      if (blogPostBuilder_ == null) {
        ensureBlogPostIsMutable();
        blogPost_.set(index, builderForValue.build());
        onChanged();
      } else {
        blogPostBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public Builder addBlogPost(de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost value) {
      if (blogPostBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlogPostIsMutable();
        blogPost_.add(value);
        onChanged();
      } else {
        blogPostBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public Builder addBlogPost(
        int index, de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost value) {
      if (blogPostBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlogPostIsMutable();
        blogPost_.add(index, value);
        onChanged();
      } else {
        blogPostBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public Builder addBlogPost(
        de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.Builder builderForValue) {
      if (blogPostBuilder_ == null) {
        ensureBlogPostIsMutable();
        blogPost_.add(builderForValue.build());
        onChanged();
      } else {
        blogPostBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public Builder addBlogPost(
        int index, de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.Builder builderForValue) {
      if (blogPostBuilder_ == null) {
        ensureBlogPostIsMutable();
        blogPost_.add(index, builderForValue.build());
        onChanged();
      } else {
        blogPostBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public Builder addAllBlogPost(
        java.lang.Iterable<? extends de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost> values) {
      if (blogPostBuilder_ == null) {
        ensureBlogPostIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blogPost_);
        onChanged();
      } else {
        blogPostBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public Builder clearBlogPost() {
      if (blogPostBuilder_ == null) {
        blogPost_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        blogPostBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public Builder removeBlogPost(int index) {
      if (blogPostBuilder_ == null) {
        ensureBlogPostIsMutable();
        blogPost_.remove(index);
        onChanged();
      } else {
        blogPostBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.Builder getBlogPostBuilder(
        int index) {
      return getBlogPostFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public de.samples.apicomparison.consumer.clients.grpc.stub.BlogPostOrBuilder getBlogPostOrBuilder(
        int index) {
      if (blogPostBuilder_ == null) {
        return blogPost_.get(index);  } else {
        return blogPostBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public java.util.List<? extends de.samples.apicomparison.consumer.clients.grpc.stub.BlogPostOrBuilder> 
         getBlogPostOrBuilderList() {
      if (blogPostBuilder_ != null) {
        return blogPostBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(blogPost_);
      }
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.Builder addBlogPostBuilder() {
      return getBlogPostFieldBuilder().addBuilder(
          de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.getDefaultInstance());
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.Builder addBlogPostBuilder(
        int index) {
      return getBlogPostFieldBuilder().addBuilder(
          index, de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.getDefaultInstance());
    }
    /**
     * <code>repeated .BlogPost blogPost = 1;</code>
     */
    public java.util.List<de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.Builder> 
         getBlogPostBuilderList() {
      return getBlogPostFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost, de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.Builder, de.samples.apicomparison.consumer.clients.grpc.stub.BlogPostOrBuilder> 
        getBlogPostFieldBuilder() {
      if (blogPostBuilder_ == null) {
        blogPostBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost, de.samples.apicomparison.consumer.clients.grpc.stub.BlogPost.Builder, de.samples.apicomparison.consumer.clients.grpc.stub.BlogPostOrBuilder>(
                blogPost_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        blogPost_ = null;
      }
      return blogPostBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListOfBlogPosts)
  }

  // @@protoc_insertion_point(class_scope:ListOfBlogPosts)
  private static final de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts();
  }

  public static de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListOfBlogPosts>
      PARSER = new com.google.protobuf.AbstractParser<ListOfBlogPosts>() {
    @java.lang.Override
    public ListOfBlogPosts parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListOfBlogPosts> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListOfBlogPosts> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.samples.apicomparison.consumer.clients.grpc.stub.ListOfBlogPosts getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

