// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogposts.proto

// Protobuf Java Version: 3.25.1
package de.samples.apicomparison.consumer.clients.grpc.stub;

public interface UUIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UUID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
