POST {{endpoint}}
Content-Type: text/xml;charset=UTF-8
SOAPAction: create

<soapenv:Envelope
  xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:blog-messages="http://samples.de/spring/soap/blog/messages">
  <soapenv:Header/>
  <soapenv:Body>
    <blog-messages:findBlogPostByIdRequest>
      <id>48120bdb-dfcb-47b7-b7ef-43f2d47b808f</id>
    </blog-messages:findBlogPostByIdRequest>
  </soapenv:Body>
</soapenv:Envelope>

> {%
  client.test("Request handled successfully", () => {
    client.assert(response.status === 200);
  });
%}
