POST {{endpoint}}
Content-Type: text/xml;charset=UTF-8
SOAPAction: create

<soapenv:Envelope
  xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:blog-messages="http://samples.de/spring/soap/blog/messages">
  <soapenv:Header/>
  <soapenv:Body>
    <blog-messages:createBlogPostRequest>
      <input>
        <title>SOAP-Test Post</title>
        <content>Das ist ein toller BlogPost.</content>
      </input>
    </blog-messages:createBlogPostRequest>
  </soapenv:Body>
</soapenv:Envelope>

> {%
  client.test("Request handled successfully", () => {
    client.assert(response.status === 200);
  });
%}
###
POST {{endpoint}}
Content-Type: text/xml;charset=UTF-8
SOAPAction: create

<soapenv:Envelope
  xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:blog-messages="http://samples.de/spring/soap/blog/messages">
  <soapenv:Header/>
  <soapenv:Body>
    <blog-messages:createBlogPostRequest>
      <input>
        <blog-messages:title>s</blog-messages:title>
        <blog-messages:content>Das ist ein toller BlogPost.</blog-messages:content>
      </input>
    </blog-messages:createBlogPostRequest>
  </soapenv:Body>
</soapenv:Envelope>

> {%
  client.test("Request handled successfully", () => {
    client.assert(response.status === 200);
  });
%}
